// apps-old/rum-records-react/src/app/main-splash-component/main-splash-component.js
import SearchBarComponent from '../search-bar-component/search-bar-component';
import styles from './main-splash-component.module.scss';

export function MainSplashComponent(props) {
  return (
    <div className={styles['splash']} style={{backgroundImage: `url("./home-splash-image.jpg"`, height: "100vh"}}>
      <div className={styles['search-bar-container']}>
        <SearchBarComponent/>
      </div>
    </div>
  );
}

export default MainSplashComponent;

// apps/rum-records-angular/src/app/main-splash/main-splash.component.ts
import { Component, OnInit } from '@angular/core';

import { SearchBarComponent } from '../search-bar/search-bar.component';

@Component({
  selector: 'rum-record-store-main-splash',
  standalone: true,
  imports: [ SearchBarComponent ],
  templateUrl: './main-splash.component.html',
  styleUrls: ['./main-splash.component.sass'],
})
export class MainSplashComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class='splash' style='height: 100vh'>
    <div class='search-bar-container'>
      <rum-record-store-search-bar></rum-record-store-search-bar>
    </div>
  </div>
