// apps/rum-records-angular/src/app/news-list/news-list.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'rum-record-store-news-list',
  standalone: true,
  templateUrl: './news-list.component.html',
  styleUrls: ['./news-list.component.sass'],
})
export class NewsListComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
  }
}

<div class='container'>
      <label data-testid='news-label' class='no-news-label'>Unable to obtain news stories.</label> 
</div>

// apps/rum-records-react/src/app/news-list-component/news-list-component.js
import styles from './news-list-component.module.scss';
export function NewsListComponent(props) {
  return (
    <div className={styles['container']} style={{height: "100vh"}}>
      {
        <label data-testid='news-label' className={styles['no-news-label']}>Unable to obtain news stories.</label> 
      }
    </div>
  );
}
export default NewsListComponent;
