// apps/rum-records-angular/src/app/app.component.ts
import { Component, ErrorHandler } from '@angular/core';
import { RouterOutlet } from '@angular/router';

import { ApmErrorHandler, ApmModule, ApmService } from '@elastic/apm-rum-angular';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faMugSaucer, faRecordVinyl } from '@fortawesome/free-solid-svg-icons';

import { environment } from '../environments/environment';

@Component({
  selector: 'rum-record-store-root',
  standalone: true,
  imports: [ApmModule, RouterOutlet, FontAwesomeModule],
  providers: [ApmService, {
      provide: ErrorHandler,
      useClass: ApmErrorHandler
    }],
  templateUrl: './app.component.html',
  styleUrl: './app.component.sass'
})
export class AppComponent {
  title = 'rum-records-angular';
  faMugSaucer = faMugSaucer;
  faRecordVinyl = faRecordVinyl;

  constructor(apmService: ApmService) {
    apmService.init({
      serviceName: 'rum-records-angular-ui',
      distributedTracingOrigins: ['http://localhost:8080'], // front to back instrumentation
      serverUrl: environment.elastic_deployment_url,
      serviceVersion: '1',
      environment: 'dev',
      // How to enable debug mode if needed
      //logLevel: 'debug'
    });
  }
}

<header>
    <a class="company-header" href="/">
      <h1 className="app-header" data-testid="company-header">
        RUM Records <fa-icon class="accent-icon" [icon]="faRecordVinyl"></fa-icon>
      </h1>
    </a>
</header>
<br />
<nav>
  <ul className="nav-bar">
    <li>
      <a href="/records">Records</a>
    </li>
    <li>
      <a href="/events">Events</a>
    </li>
    <li>
      <a href="/news">News</a>
    </li>
  </ul>
</nav>
<hr />
<section>
    <router-outlet></router-outlet>
</section>
<footer>
  Made by Carly Richmond with love and excessive amounts of tea
  <fa-icon class="accent-icon footer-icon" [icon]="faMugSaucer"></fa-icon>
</footer>

// apps/rum-records-react/src/app/app.js
import { Link } from 'react-router-dom';

import { faMugSaucer, faRecordVinyl } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { init as initApm } from '@elastic/apm-rum';
import { ApmRoute } from '@elastic/apm-rum-react';

import styles from './app.module.scss';
import { environment } from '../environments/environment';
import MainSplashComponent from './main-splash-component/main-splash-component';
import EventListComponent from './event-list-component/event-list-component';
import NewsListComponent from './news-list-component/news-list-component';
import SearchRecordsComponent from './search-records-component/search-records-component';

export function App() {

  initApm({
    serviceName: 'rum-records-react-ui',
    distributedTracingOrigins: ['http://localhost:3333'], // front to back instrumentation
    serverUrl: environment.elastic_deployment_url,
    serviceVersion: '1',
    environment: 'dev'
  });

  return (
    <>
      <header>
          <Link className={styles['company-header']} to="/">
            <h1 className={styles['app-header']} data-testid="company-header">
              RUM Records <FontAwesomeIcon icon={faRecordVinyl} />
            </h1>
          </Link>
      </header>
      <br />
      <nav>
        <ul className="nav-bar">
          <li>
            <Link to="/records">Records</Link>
          </li>
          <li>
            <Link to="/events">Events</Link>
          </li>
          <li>
            <Link to="/news">News</Link>
          </li>
        </ul>
      </nav>
      <hr />
      <section>
          <ApmRoute
            path="/"
            exact
            component={MainSplashComponent}
          />
          <ApmRoute
            path="/records"
            component={SearchRecordsComponent}            
          />
          <ApmRoute
            path="/events"
            component={EventListComponent}
          />
          <ApmRoute
            path="/news"
            component={NewsListComponent}
          />
      </section>
      <footer>
        Made by Carly Richmond with love and excessive amounts of tea
        <FontAwesomeIcon icon={faMugSaucer} />
      </footer>
    </>
  );
}
export default App;
