// apps/rum-records-angular/src/app/news-list/news-list.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'rum-record-store-news-list',
  standalone: true,
  templateUrl: './news-list.component.html',
  styleUrls: ['./news-list.component.sass'],
})
export class NewsListComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
      throw new Error ('Unable to get news stories');
  }

  onSubscribeClick() {
    alert('Thank you for subscribing!');
  }
}

<div class='container'>
      <label data-testid='news-label' class='no-news-label'>Unable to obtain news stories.</label> 

      <button class="subscribe-btn" data-testid="subscribe-btn" 
            (click)="onSubscribeClick()">Subscribe</button>
</div>

// apps/rum-records-react/src/components/news-list-component/news-list-component.js
import axios from 'axios';
import { faWarning } from '@fortawesome/free-solid-svg-icons';
import { useEffect } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { environment} from '../../environments/environment';

import './news-list-component.css';

export function NewsListComponent(props) {
  useEffect(() => {
    async function getNews() {
      try {
        let url = `${environment.baseUrl}/error/`;
        axios.get(url).then(res => {
          console.log(res);
      }).catch(errorRes => {
        console.log(errorRes.message);
      });
      }
      catch(err) {
        console.log('Unable to get news stories');
      }
    }
    getNews();
  });

  function onSubscribeClick() {
    alert('Thank you for subscribing!');
  }

  return (
    <div className="container" style={{height: "100vh"}}>
        <label data-testid="news-label" className="no-news-label"><FontAwesomeIcon icon={faWarning} />Unable to obtain news stories.</label> 
        <button class="subscribe-btn" data-testid="subscribe-btn" 
          onClick={onSubscribeClick}>Subscribe</button> 
    </div>
  );
}
export default NewsListComponent;
