// apps/rum-records-angular/src/app/record-card/record-card.component.ts
import { Component, Input } from '@angular/core';
import { faCompactDisc, faFileAudio, faRecordVinyl } from '@fortawesome/free-solid-svg-icons';
import { MusicRecord } from '../record-list/music-record';

@Component({
  selector: 'rum-record-store-record-card',
  templateUrl: './record-card.component.html',
  styleUrls: ['./record-card.component.sass'],
})
export class RecordCardComponent {

  @Input()
  public record!: MusicRecord;

  protected formatIconMap = {
    'LP': faRecordVinyl,
    'CD': faCompactDisc,
    'DD': faFileAudio
  };
}

<div class='record-card' data-testid='record-card'>
    <img [src]='record.imagePath' alt='Record'/>
    <div class='record-details'>
        <h2>{{record.title}}</h2>
        <h3>{{record.artist}}</h3>
        <div class='available-formats'>
        <label class='available-formats-label'>Available formats</label>
            <div data-testid='format-icon-collection' class='format-icons'>
                <fa-icon *ngFor='let format of record.formats' class='accent-icon' 
                [icon]='formatIconMap[format]'></fa-icon>
                <label class='no-formats-available-label' *ngIf='record.formats.length === 0'>N/A</label>
            </div>
        </div>
    </div>
</div>

// apps/rum-records-react/src/components/record-card-component/record-card-component.js
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCompactDisc, faFileAudio, faRecordVinyl } from '@fortawesome/free-solid-svg-icons';

import './record-card-component.css';

export function RecordCardComponent(props) {

  const formatIconMap = {
    'LP': faRecordVinyl,
    'CD': faCompactDisc,
    'DD': faFileAudio
  };

  return (
    <div className="record-card" data-testid='record-card'>
      <img src={props.record.imagePath} alt='Record'/>
    <div className="record-details">
      <h2>{props.record.title}</h2>
      <h3>{props.record.artist}</h3>
      <div className="available-formats">
        <label className="available-formats-label">Available formats</label>
        <div data-testid='format-icon-collection' className="format-icons">
        { props.record.formats.length > 0 ?
        props.record.formats.map((format, index) => 
        (<FontAwesomeIcon key={index} icon={formatIconMap[format]}/>)
        ) : 
        <label className="no-formats-available-label">N/A</label>}
        </div>
      </div>
    </div>
  </div>
  );
}
export default RecordCardComponent;
