// apps/rum-records-angular/src/app/search-bar/search-bar.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import { faSearch } from '@fortawesome/free-solid-svg-icons';

@Component({
  selector: 'rum-record-store-search-bar',
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.sass'],
})
export class SearchBarComponent implements OnInit {

  public terms: string;
  faSearch = faSearch;

  constructor(private _router: Router, private route: ActivatedRoute) {
    this.terms = '';
  }

  ngOnInit(): void {
    this.route.queryParams.subscribe(params => {
      this.terms = params['terms'];
    })
  }

  public searchRecords() {
    this._router.navigateByUrl(`/records?terms=${this.terms?.toLowerCase()}`)
    return;
  }
}

// apps/rum-records-react/src/components/search-bar-component/search-bar-component.js
import { faSearch } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useNavigate } from 'react-router-dom';

import './search-bar-component.css';

export function SearchBarComponent(props) {

  const navigate = useNavigate();

  function searchRecords(event) {
    if (event?.key === 'Enter') {
      const queryTerms = event.currentTarget.value.toLowerCase();
      navigate(`/records?terms=${queryTerms}`);
    }
  }

  return (
    <div className="searchContainer">
        <FontAwesomeIcon icon={faSearch} />
        <input defaultValue={props.query} type="search" placeholder="Browse our record selection today!" 
        aria-label="Search record selection" onKeyUp={searchRecords}></input>
      </div>
  );
}
export default SearchBarComponent;
